// apps/magic-mile/src/app/components/results-table/results-table.component.ts
import { Component, Input, OnChanges } from '@angular/core';
import { MagicMile } from '@black-pear-joggers/magic-mile-data-access';

@Component({
  selector: 'bpj-results-table',
  templateUrl: './results-table.component.html',
  styleUrls: [ './results-table.component.scss' ],
})
export class ResultsTableComponent implements OnChanges {
  @Input() results: MagicMile[];
  @Input() resultsPerPage = 100;
  @Input() sort: string;
  currentPage = 1;
  sortedResults: MagicMile[];

  ngOnChanges() {
    if (this.sort === 'fastest') {
      this.sortedResults = this.results.slice(0).sort((result1, result2) => (result1.actualTime < result2.actualTime ? -1 : 0));
    } else {
      this.sortedResults = this.results;
    }
  }

  previousPage() {
    if (this.currentPage > 1) {
      this.currentPage--;
    }
  }

  nextPage() {
    if (this.endRecord < this.results.length) {
      this.currentPage++;
    }
  }

  get startRecord() {
    return this.resultsPerPage * this.currentPage - this.resultsPerPage + 1;
  }

  get endRecord() {
    const endRecord = this.resultsPerPage * this.currentPage;

    return endRecord > this.results.length ? this.results.length : endRecord;
  }
}

<table
  *ngIf="results && results.length"
  class="table table--large"
>
  <thead>
    <tr>
      <th>Name</th>

      <th>Predicted</th>

      <th>Actual</th>

      <th>Standards</th>

      <th>Date</th>

      <th class="u-hidden@max-xs">Gender</th>

      <th class="u-hidden@max-xs">Category</th>

      <th class="u-hidden@max-sm">Location</th>
    </tr>
  </thead>

  <tbody>
    <tr *ngFor="let result of sortedResults | limit : startRecord : endRecord">
      <td nowrap="nowrap">
        <a href="https://bpj.org.uk/records-and-rankings/race-results/#/athlete/{{ result.athleteId }}" *ngIf="result.athleteId">
            {{ result.firstName }} {{ result.lastName }}
        </a>

        <ng-template [ngIf]="!result.athleteId">
            {{ result.firstName }} {{ result.lastName }}
        </ng-template>
      </td>

      <td [attr.data-sort-value]="result.predictedTime">{{ result.predictedTime | finishTime }}</td>

      <td [attr.data-sort-value]="result.actualTime">
        {{ result.actualTime | finishTime }}

        <span class="pb" *ngIf="result.isPersonalBest">PB</span>
      </td>

      <td class="athlete-results__award nowrap standards__heading--{{result.award | formatAward}}">
        <a class="link" href="https://apps.bpj.org.uk/club-standards/">{{result.award | formatAward}}</a>
      </td>

      <td>{{ result.date | date: "D MMM YY" }}</td>

      <td class="u-hidden@max-xs">{{ result.gender | gender }}</td>

      <td class="u-hidden@max-xs"><abbr title="{{ result.category | category }}">{{ result.category }}</abbr></td>

      <td class="u-hidden@max-sm">{{ result.location }}</td>
    </tr>
  </tbody>
</table>

<div *ngIf="results" class="pagination">
  <p>
    Showing
    {{ startRecord }}
    to
    {{ endRecord }}
    of
    {{ results.length }}
  </p>

  <a class="pagination__link pagination__link--previous" (click)="previousPage()" href="javascript:void(0)">Previous Page</a>

  <a class="pagination__link pagination__link--next" (click)="nextPage()" href="javascript:void(0)">Next Page</a>
</div>

// next/apps/results/components/results-table.tsx
import Link from 'next/link';
import { AwardBadge } from './award-badge';
import { Performance } from '@black-pear-joggers/core-services';

type ResultsTableProps = {
  results: Performance[];
};

export const ResultsTable = ({ results }: ResultsTableProps) => {
  if (!results || !results.length) return null;

  return (
    <table className="w-full">
      <thead className="divide-y divide-gray-200">
        <tr>
          <th className="px-4 py-2">Date</th>
          <th className="px-4 py-2">Athlete</th>
          <th className="px-4 py-2">Event</th>
          <th className="px-4 py-2">Event name</th>
          <th className="px-4 py-2">Gender</th>
          <th className="px-4 py-2">Category</th>
          <th className="px-4 py-2">Time</th>
          <th className="px-4 py-2">Standard</th>
        </tr>
      </thead>
      <tbody className="divide-y divide-gray-200">
        {results.map((result, index) => (
          <tr key={result.id} className={index % 2 === 0 ? 'bg-gray-100' : ''}>
            <td className="px-4 py-2">{result.date}</td>
            <td className="px-4 py-2">
              {result.membershipStatus === 'Registered' ? (
                <Link
                  href={`https://apps.bpj.org.uk/race-results/#/athlete/${result.athleteId}`}
                >
                  {result.firstName} {result.lastName}
                </Link>
              ) : (
                <>
                  {result.firstName} {result.lastName}
                </>
              )}
            </td>
            <td className="px-4 py-2">{result.event}</td>
            <td className="px-4 py-2">{result.meetingName}</td>
            <td className="px-4 py-2">
              {result.gender === 'M' ? 'Male' : 'Female'}
            </td>
            <td className="px-4 py-2">{result.category}</td>
            <td className="px-4 py-2">
              {result.time} {result.isPersonalBest ? ' (PB)' : ''}
            </td>
            <td className="px-4 py-2">
              <AwardBadge award={result.award} />
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
};
