// next/libs/footer/src/lib/footer.tsx
import Link from 'next/link';

interface FooterLinkProps {
  link: string;
  text: string;
}

const FooterLink = ({ link, text }: FooterLinkProps) => (
  <li>
    <Link href={link}>
      <a className="md:mx-3 no-underline hover:underline">{text}</a>
    </Link>
  </li>
);

export const Footer = () => (
  <footer className="text-center bg-gray-900 text-white py-8">
    <img
      src="https://bpj.org.uk/wp-content/themes/BPJ/england-athletics-logo.svg"
      alt="England Athletics"
      width="200"
      height="68"
      className="mb-8 mx-auto"
    />

    <ul className="flex flex-col space-y-4 md:space-y-0 md:flex-row justify-center">
      <FooterLink link="/club-constitution" text="Club constitution" />

      <FooterLink
        link="/health-and-safety-policy-and-risk-assessment"
        text="Health and safety policy"
      />

      <FooterLink link="/privacy-policy" text="Privacy policy" />

      <FooterLink link="/terms-of-use" text="Terms of use" />

      <FooterLink link="/site-map" text="Site map" />
    </ul>
  </footer>
);

// libs/shared-components/src/lib/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'bpj-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent implements OnInit {
  constructor() {}

  ngOnInit() {}
}

<footer>
  <ul class="links">
    <li>
      <a href="https://bpj.org.uk/club-constitution/">Club Constitution</a>
    </li>
    <li>
      <a href="https://bpj.org.uk/health-and-safety-policy-and-risk-assessment/">Health and Safety Policy</a>
    </li>
    <li>
      <a href="https://bpj.org.uk/privacy-policy/">Privacy Policy</a>
    </li>
    <li>
      <a href="https://bpj.org.uk/terms-of-use/">Terms of Use</a>
    </li>
  </ul>
</footer>
